"""Completed setting the relationships

Revision ID: bdf576d3ca9d
Revises: 008a1e1a986c
Create Date: 2023-09-04 17:28:49.786718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf576d3ca9d'
down_revision: Union[str, None] = '008a1e1a986c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shuttles', sa.Column('sacco_id', sa.Integer(), nullable=True))
    op.add_column('shuttles', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shuttles', 'saccos', ['sacco_id'], ['id'])
    op.create_foreign_key(None, 'shuttles', 'members', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shuttles', type_='foreignkey')
    op.drop_constraint(None, 'shuttles', type_='foreignkey')
    op.drop_column('shuttles', 'owner_id')
    op.drop_column('shuttles', 'sacco_id')
    # ### end Alembic commands ###
